# Generated by Django 4.1.4 on 2023-01-20 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0003_alter_movie_created_alter_movie_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_value', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_value', to=settings.AUTH_USER_MODEL),
        ),
    ]
