# Generated by Django 4.1.4 on 2023-01-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_actor_id_alter_movie_director_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Actor_id',
            field=models.ManyToManyField(to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Director_id',
            field=models.ManyToManyField(to='movie.director'),
        ),
    ]
