# Generated by Django 4.1.4 on 2023-01-14 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_actor_id_alter_movie_director_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raiting',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='raitingValue',
            new_name='ratingValue',
        ),
    ]
